### ISSUE TITLE
couple questions

### ISSUE THREAD

**Issue by foxpcteam** [patchdotworks/prism#1]
Hi,
good luck with the project!

couple questions:
1.as i understand this plugin will allow you to change the wp-admin to something that you can customize as you want and of curse speed! (web app) am i right?

2 do you plan to add RTL Support?

**Comment by caseypatrickdriscoll** [comment]
Hello there!

1. Not quite. This plugin will have nothing to do with wp-admin, it takes over the front end of the application only. The wp-admin will still function like normal. (I can see how it looks similar, but will be separate). It's a framework for building custom apps.

2. Didn't even occur to me until now! I'll add it as a feature-enhancement (I'm not even sure what is needed here. Do you mean just the text or the panels themselves?)

Cheers!

**Comment by foxpcteam** [comment]
Hi,
1. but your plugin will allow us to create posts, page and etc without entering the wp-admin?
2. i mean text and panels.

**Comment by caseypatrickdriscoll** [comment]
1. That’s the idea. If you install it at this point, you should be able to read and add stuff. Let me know if more q’s on how to use it. Just in the early hours still, no docs set up yet.

On October 15, 2015 at 2:54:25 PM, foxpcteam (notifications@github.com) wrote:

Hi,
1. but your plugin will allow us to create posts, page and etc without entering the wp-admin?
2. i mean text and panels.

**Comment by caseypatrickdriscoll** [comment]
Closing this for now, but feel free to ask any more questions.
